### ISSUE TITLE
Separating html & js in bde elements breaks BDE-element-API-documentation

### ISSUE THREAD

**Issue by erne-mt** [cubbles/bde#2]
Is there any reason, why the elements are separated in (style) html and script files, although they build single particular element?

I have the problem that the documentation via iron-component-page breaks because of this reason.

**Comment by jtrs** [comment]
Because a pure js file can lint with eslint. And it is more confortable for develop longer code.

**Comment by erne-mt** [comment]
Ok, I can go with that.

But Polymer elements are conceptually designed to be a single entity both view and script (as well as some dependencies)

So what about [polylint](https://github.com/PolymerLabs/polylint) ?

**Comment by jtrs** [comment]
I think, this is just a problem of locally development.  The base uses already HTTP2, and therefore  it is not really a problem anymore.

**Comment by erne-mt** [comment]
@jtrs Your answer refers to the #3 pull request, doesn't it?

**Comment by jtrs** [comment]
Both, its applies to this issue and to the pull request

**Comment by mplabs** [comment]
The main issue was not addressed here. Not concatenating the elements into a single file breaks automatic documentation which is a major issue. I would like to see this addressed, or otherwise solved.

**Comment by erne-mt** [comment]
maybe is related to [polymer-analyzer issue](https://github.com/Polymer/polymer-analyzer/issues/119#issuecomment-112963716) and [another](https://github.com/Polymer/polymer-analyzer/issues/190) and a possible solution in [this issue](https://github.com/Polymer/polymer-analyzer/issues/224) ( - JSDoc Magic).

**Comment by erne-mt** [comment]
A possible solution is annotating the script files with an _@importedBy ELEMENT.HTML_ comment.

@mplabs and @iskandar992 were working on a grunt-based solution with the use of [polymer-analyzer](https://github.com/Polymer/polymer-analyzer)

**Comment by erne-mt** [comment]
Well, it is still not completely solved, but with _@importedBy_ we have at least a start. 

The [issue](https://github.com/PolymerElements/iron-component-page/issues/108) with iron-component-page will still be open, and I hope the issue displaying the annotations of properties and methods will be somehow resolved by the Polymer team, possibly by including a newer analyzer version in iron-component-pages.

So I will close this for now and continue the documentation as far as possible, but as I am still working on this, I will keep this in mind.
